services:
  postgres:
    image: postgres:latest
    container_name: postgres_db
    environment:
      POSTGRES_DB: brt_data
      POSTGRES_USER: docker
      POSTGRES_PASSWORD: secreta
    volumes:
      - postgres-data:/var/lib/postgresql/data
    ports:
      - 5432:5432
  
volumes: 
  postgres-data: